### ISSUE TITLE
Master branch fails to build

### ISSUE THREAD

**Issue by kusuri** [SpartanJ/efsw#1]
The commit a5e088947f4c07d26126b6fc11924575edcc809a does not build successfully.

See the error below (file `src/efsw/FileWatcherKqueue.cpp:121:13`)
![Screen Shot 2019-03-22 at 18 55 56](https://user-images.githubusercontent.com/7706803/54839737-2dff6200-4cd4-11e9-96ff-4e2da6cb36a6.png)

**Comment by kusuri** [comment]
Is this a possible a solution?

```c++
if ( EACCES != le )
{
    WatcherGeneric * watch = new WatcherGeneric( ++mLastWatchID, dir, watcher, this, recursive );

    Lock lock( mWatchesLock );
    mWatches.insert(std::make_pair(mLastWatchID, watch));
}
```

**Comment by SpartanJ** [comment]
You are right. I don't know how this compiled before. But the KQueue backend is old, so is possible. Thank you for letting me know! [I committed a fix already.](https://bitbucket.org/SpartanJ/efsw/commits/2d1d8e06953c2bf77fccb60ecbc0e84915ee3ac5)
