### ISSUE TITLE
UWP support

### ISSUE THREAD

**Issue by Pospelove** [SpartanJ/efsw#108]
Hello. Does this library support UWP? Are you planning to support this platform in the future?

**Comment by SpartanJ** [comment]
Hi!
No, it's not supported, I think it doesn't make much sense either, UWP has several limitations and this library kinda low-level for UWP. It might be possible to make it work though, I'm not familiar enough with UWP to know. Of course, feel free to check it out if that interests you.
But, I think that you just need to disable the UWP build for the new package. AFAIK there are tones of libraries without UWP support in `vcpkg`, they just disable the UWP build. [Here's](https://github.com/microsoft/vcpkg/pull/11648/commits/8149994c2dd1b6b26d4eb7dc67282c6e29e6372b) an example of how to disable it.

**Comment by SpartanJ** [comment]
BTW, don't enable the verbose mode for the `vcpkg` build, that's only there for debugging purposes, it shouldn't be enabled for production or distribution.
Also, the patch shouldn't be necessary, that change has already been merged, just change the `REF` the the latest commit (`b62d04829bb0a6f3cacc7859e0b046a3c053bc50`).

**Comment by Pospelove** [comment]
@SpartanJ Thanks. I have disabled uwp for now. Asked just to verify it's right.
