### ISSUE TITLE
FileWatcherFSEvents: random crashes when unwatching a directory

### ISSUE THREAD

**Issue by merwaaan** [SpartanJ/efsw#112]
Hi @SpartanJ ,
I'm struggling to understand an efsw crash that occurs only when running stress tests on OSX.

At some point in my application, I unwatch a directory. This leads to this code getting executed:

- `FileWatcherFSEvents::removeWatch()`
  - `WatcherFSEvents::~WatcherFSEvents()`
    - `FSEventStreamStop()`
    - `FSEventStreamInvalidate()`
    - `FSEventStreamRelease()`
  - `efSAFE_DELETE(watch)`

At this point, events should stop and the watcher is NULL.

However, the event callback `FileWatcherFSEvents::FSEventCallback` is sometimes called right after this anyway, even though we just used `FSEventStreamStop()`.
The callback retrieves the watcher passed as "user data" and calls `watcher->handleActions()`, which crashes since it has been previously deleted.

This does not always happen, I have a unit test that produces a crash ~ half the times but unfortunately it's too tied to my application to share it at the moment.

**Do you have any idea why this happens?
I'm not too familiar with the OSX API but I expected `FSEventStreamStop()` to be effective immediately, does it seem wrong to you?
Could this be due to some concurrency issue?**

Thanks

**Comment by SpartanJ** [comment]
This totally looks like a concurrency issue, we can sort it out with some checks. Can you share a minimal example to reproduce the bug? I will take a look at this at the weekend. Thanks!

**Comment by merwaaan** [comment]
I solved my issue while preparing a minimal example!

What happened was that in some cases I unwatched a directory IN the event callback (well not exactly "in" but from code called indirectly by the event callback).

So basically:
- `WatcherFSEvents::handleActions()` called when an event occurs
  - `WatcherFSEvents::sendFileAction` triggers my custom event callback
    - [ ... some application code ... ]
      - high-level `watcher->removeWatch()` with the same directory as the event that's currently processed  
  - back to `WatcherFSEvents::handleActions`, the efsw code expects the watcher to still be valid so it crashes

So not a concurreny issue and `FSEventStreamStop()` seems to behave as expected.

By chance, it did not crash with the Windows watcher but only with the OSX one so I didn't notice this earlier.

In any case, I'd say it's as much a user error as a bug so I'm not sure if it really needs fixing ;)

**Comment by SpartanJ** [comment]
Oh, I didn't think about that, yeah, this is kinda a limitation on how FSStreams works, since it uses a callback for the events. Maybe I should add a note in the project readme file to acknowledge this situation. You should be able to sort it out just by calling the remove in another thread. I'll keep the issue open so I don't forget to at least add that note. Thanks for the investigation!
Also: If by any chance you can share to the project the unit tests that you are creating to test efsw it would be awesome to add them here. I always wanted to add some tests but I'm a little lazy.

**Comment by merwaaan** [comment]
About the unit tests: unfortunately those are not efsw-specific unit tests but rather application-specific unit tests that sometimes rely on efsw, so I'm afraid they're too tied to my application and they're of no value to efsw :)
