### ISSUE TITLE
macOS crash on teardown

### ISSUE THREAD

**Issue by spaderthomas** [SpartanJ/efsw#126]
Hi. Our product experienced a crash on teardown, and we traced it back to EFSW. We're using the FSEvents implementation, and the crash is a segfault in `CFStopRunLoop` when the thread is being torn down in `efsw::FileWatcherFSEvents::~FileWatcherFSEvents`. The usage is [here](https://github.com/SpartanJ/efsw/blob/master/src/efsw/FileWatcherFSEvents.cpp#L232). I believe this call to `CFStopRunLoop` is unnecessary and can be removed.

Per the [Apple Developer documentation](https://developer.apple.com/documentation/corefoundation/1541796-cfrunloopstop):
```
This function forces rl to stop running and return control to the function that called CFRunLoopRun or CFRunLoopRunInMode for the current run loop activation.
```
However, there is no current run loop activation at the moment it is called, so the call to stop it is unnecessary.

Attached is a crash report with irrelevant company-specific information stripped.
[crash-report-stripped-2.txt](https://github.com/SpartanJ/efsw/files/7227678/crash-report-stripped-2.txt)

**Comment by SpartanJ** [comment]
Hi!
Thanks for reporting it. 
I tried to reproduce the bug but it doesn't crash here. Calling `CFStopRunLoop` when `CFRunLoopRunInMode` should have no effect (so it's incorrect to have that there), but I don't understand how it crashes. Do you have a minimal example to reproduce it?
So... your observation is correct, the call does not make sense at all. It should be called in the object destructor to stop the `CFRunLoopRunInMode` execution (so the thread wait call does not lock the object destruction). But first I want to understand why it crashes in the first place.
I made a commit [here](https://github.com/SpartanJ/efsw/commit/d68d5cab9c47e6fb8b4986064f1a7b15e31e94bd) that changes where this run loop is stopped, but it could still fail if in your case crashes when there is no active run loop in execution.

**Comment by spaderthomas** [comment]
Unfortunately, I do not have an example to reproduce it. This crash occurred on an old product version, and cannot be reproduced. All we have is the crash report I linked in the original issue. I also could not figure out why `CFStopRunLoop` would cause a crash with that incorrect usage. 

I believe the commit you linked will fix the underlying issue.

I'm sorry I can't be more helpful with this, but I will report back if the crash happens again with the new commit. Thank you!

**Comment by SpartanJ** [comment]
No problem. Thanks for your help. Keep me updated if any other issue appears. BTW, I'm interested in knowing where efsw is being used, can you tell me what's the name of the application (if it's public). I would love to add into the efsw repo README a list of applications using it.
I'll close the issue, feel free to open it again if necessary.
Thanks!

**Comment by spaderthomas** [comment]
Sorry, I can't disclose what the application is 😅

**Comment by SpartanJ** [comment]
No problem, if that changes at some point in time just let me know. Thanks
