### ISSUE TITLE
Occasional crash on MacOS

### ISSUE THREAD

**Issue by vyunikov** [SpartanJ/efsw#127]
Our app uses efsw library to monitor FS for changes.
Based on crash reports from out users, app is occasionally crashing when efsw is being initialized.
Stack trace looks like this:
libefsw.dylib  efsw::WatcherFSEvents::initAsync() WatcherFSEvents.cpp:78
libefsw.dylib  efsw::FileWatcherFSEvents::run() FileWatcherFSEvents.cpp:223
libefsw.dylib  efsw::Platform::ThreadImpl::entryPoint(void*) ThreadImpl.cpp:61
libsystem_pthread.dylib  _pthread_start
libsystem_pthread.dylib thread_start

The following line is causing a crash:
```
FSEventStreamScheduleWithRunLoop( FSStream, FWatcher->mRunLoopRef, kCFRunLoopDefaultMode );
```

Do you have an idea, why it might be crashing?

**Comment by SpartanJ** [comment]
I have no idea. Do you have any hints on how and when is initialized? Can I test your application on me macOS setup? The source is available?
Thanks

**Comment by vyunikov** [comment]
I am not doing any specific initialization. What I do is I just create watcher when needed, and that's when I guess initialization happens. Unfortunately I cannot reproduce the crash myself, it just happens rarely for some users (I see the crash reports). 
Unfortunately I cannot provide you with the code, as our code is not publicly available.

**Comment by SineStriker** [comment]
I started to use this library several days ago and I hope this problem could be fixed as soon as possible.

**Comment by SpartanJ** [comment]
Are you experiencing the same issue? Can you provide some information?

**Comment by SineStriker** [comment]
Not yet. I just worry about it.

**Comment by SpartanJ** [comment]
@vyunikov is there any relevant information that you can add to the current information? Maybe how many watches were created, if they were recursive, or if you add and remove watches intensively? Thanks

**Comment by SineStriker** [comment]
Also find occasional crash under windows and linux, every crash occurs when removeWatch is called.
