### ISSUE TITLE
TSan detects data races on OSX

### ISSUE THREAD

**Issue by IohannRabeson** [SpartanJ/efsw#129]
Hi! I was about to use this library and I stumbled upon https://github.com/SpartanJ/efsw/issues/127 so I wanted to investigate a little bit using sanitizers. I just found TSAN detects several issues on OSX when the test application startup, I think it worth investigating them -  and I did not try on other platforms but I guess you might get other similar issues.

I attached the log output I got using Clang and thread sanitizer enabled (using https://github.com/arsenm/sanitizers-cmake because I'm lazy). To reproduce my test yourself, I provide you this branch https://github.com/IohannRabeson/efsw/tree/enable_sanitizers where I just added as a submodule sanitizers-cmake and modified the CMake configuration to plug it in. I generated the project with the following CMake arguments:   
`-DBUILD_TEST_APP=ON -DSANITIZE_THREAD=ON -DCXX11=ON`
To run the test, I created folders test and test2 into the working directory before, then I started the test application, then I closed it. 
[t_san_report.txt](https://github.com/SpartanJ/efsw/files/7324582/t_san_report.txt)

**Comment by SpartanJ** [comment]
Finally fixed these issues. Thanks!
