### ISSUE TITLE
Items in subdirectories of watched directories on Linux return events under a different watch ID

### ISSUE THREAD

**Issue by jg-x2x** [SpartanJ/efsw#140]
If you have a directory structure like this:

```
dir - fileA
   \- subdir - fileB
```

and you add a watch for `dir`, it gets watchID 1. Actions that happen to `fileA` or `subdir` itself are raised for watchID 1 as expected. Events that happen to `fileB` are raised for watchID 2 and are thus missed by client code looking for events related to the ID it was given. Considering this doesn't happen on any platform other than Linux, I presume it to be a bug?

Tested on CentOS 7 and CentOS 9

**Comment by SpartanJ** [comment]
Hi! Yes, this is accidental. PR #139 will solve this issue.

**Comment by jg-x2x** [comment]
Good to hear. Thanks for confirming.

**Comment by SpartanJ** [comment]
Fixed.
