### ISSUE TITLE
How to use QT-Creator to open the project 'qtreator-win' ?

### ISSUE THREAD

**Issue by Rachy1989** [SpartanJ/efsw#141]
Hi, SpartanJ
I am a novice in QT programming. I need to use qt-5.6.3 to compile efsw, but don't know how to use the project ‘project/qtcreator-win’，I need your help.  Thanks.

**Comment by SpartanJ** [comment]
It won't help you much, that's my personal project file, and it won't translate fine to other systems. But if you want yo use it, just rename the "efsw.creator.user" file to "efsw.creator.shared" and open the "efsw.creator" project file.

**Comment by Rachy1989** [comment]
OK, Thanks.
