### ISSUE TITLE
CMake multi config issue

### ISSUE THREAD

**Issue by ypujante** [SpartanJ/efsw#150]
This [section](https://github.com/SpartanJ/efsw/blob/master/CMakeLists.txt#L119) in the `CMakeLists.txt` 

```cmake
if (${CMAKE_BUILD_TYPE} MATCHES "Debug")
	target_compile_definitions(efsw PRIVATE DEBUG)
elseif (${CMAKE_BUILD_TYPE} MATCHES "Release")
	target_compile_definitions(efsw PRIVATE NDEBUG)
endif()
```

is not working properly when using a multi config generator (like Xcode).

If you replace it with this:

```cpp
target_compile_definitions(efsw PRIVATE $<IF:$<CONFIG:Debug>,DEBUG,NDEBUG>)
```

then it fixes the issue (and works in all cases).

See this CMake documentation about this [problem](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#build-configurations)

**Comment by SpartanJ** [comment]
Great, thanks, I'll patch it later!

**Comment by ypujante** [comment]
Thank you. And thanks for your library. I am using it in my open source project: https://github.com/pongasoft/re-edit
