### ISSUE TITLE
Check Return Code and Allow Buffer Customization in `ReadDirectoryChangesW()` Function

### ISSUE THREAD

**Issue by solarispika** [SpartanJ/efsw#153]
From https://github.com/SpartanJ/efsw/issues/142#issuecomment-1427591056

Currently, the function that uses the `ReadDirectoryChangesW()` function does not check its return code, and this makes it difficult for users to detect and respond to failures. Therefore, I would like to request that the function checks the return code of the ReadDirectoryChangesW() function to ensure that it has executed successfully. This will enable users to react accordingly if the function call fails.

Additionally, I suggest allowing users to customize the size of the buffer or provide the buffer themselves. This would provide users with more control over the function, allowing them to tailor the buffer to their specific needs.

By adding these features, users will have greater control over the `ReadDirectoryChangesW()` function, making it easier for them to detect failures and customize the function to their specific requirements.

**Comment by solarispika** [comment]
Status update:

- [x] Custom buffer size: Implemented in https://github.com/SpartanJ/efsw/pull/162
- [ ] Error handling: Although https://github.com/SpartanJ/efsw/pull/164 refreshes watches when they overflowed, but users are not noticed and some events may be lost. It would be better for user to be informed in this case.

**Comment by SpartanJ** [comment]
I'll close due to inactivity, major problem has been solved long time a go.
