### ISSUE TITLE
Premake5 macosx after gmake2 ... [CI Server]

### ISSUE THREAD

**Issue by jackokring** [SpartanJ/efsw#158]
```
cd efsw/make/macosx && make config=release
Makefile:42: *** "invalid configuration release".  Stop.
make: *** [libefsw.a] Error 2
Error: Process completed with exit code 2.
```

I have no access to server except push and test.

**Comment by SpartanJ** [comment]
Please read my comment on your previous issue [here](https://github.com/SpartanJ/efsw/issues/156#issuecomment-1457460531).
`config=release` is *invalid*
