### ISSUE TITLE
Visual studio creates multiple files on save 

### ISSUE THREAD

**Issue by Dunk-Master** [SpartanJ/efsw#165]
![Untitlelljkkd](https://github.com/SpartanJ/efsw/assets/126705166/4b724e2c-8f19-4420-8083-52e86699fd1c)
Visual studio creates multiple files on save but notepad does not. How do i navigate around this?

**Comment by SpartanJ** [comment]
You'll have to track the file changes, this is not a problem with efsw, but on how VS creates, modifies and delete files, I can't do anything about it. I don't know what you're trying to achieve so I can't give you any advice, sorry.

**Comment by Dunk-Master** [comment]
1.How do i track the file changes?
2. Am trying to achieve the similar thing in notepad.

**Comment by Dunk-Master** [comment]
So if anyone is using visual studio, they are doomed?

**Comment by Dunk-Master** [comment]
wow

**Comment by Dunk-Master** [comment]
https://godbolt.org/z/jTGh71Yd5
