### ISSUE TITLE
memory leak doubt and thread conflict

### ISSUE THREAD

**Issue by hgyxbll** [SpartanJ/efsw#174]
memory leak doubt:
at WatcherWin32.cpp.
CreateWatch use below code.
```c
/// Starts monitoring a directory.
WatcherStructWin32* CreateWatch( LPCWSTR szDirectory, bool recursive, DWORD NotifyFilter,
								 HANDLE iocp ) {
	WatcherStructWin32* tWatch;
	size_t ptrsize = sizeof( *tWatch );
	tWatch = static_cast<WatcherStructWin32*>(
		HeapAlloc( GetProcessHeap(), HEAP_ZERO_MEMORY, ptrsize ) );   // there malloc 
```

DestroyWatch use below code.
```c
void DestroyWatch( WatcherStructWin32* pWatch ) {
	if ( pWatch ) {
		WatcherWin32* tWatch = pWatch->Watch;
		tWatch->StopNow = true;
		CancelIoEx( pWatch->Watch->DirHandle, &pWatch->Overlapped );
		CloseHandle( pWatch->Watch->DirHandle );
		efSAFE_DELETE_ARRAY( pWatch->Watch->DirName );
		efSAFE_DELETE( pWatch->Watch );
	}
}
```
this do not HeapFree pWatch.

Is it may leak memory?

Thread conflict:
at FileWatcherWin32.cpp.
```c++
void FileWatcherWin32::run() {
	do {
		if ( mInitOK && !mWatches.empty() ) {
			DWORD numOfBytes = 0;
			OVERLAPPED* ov = NULL;
			ULONG_PTR compKey = 0;
			BOOL res = FALSE;

			while ( ( res = GetQueuedCompletionStatus( mIOCP, &numOfBytes, &compKey, &ov,
													   INFINITE ) ) != FALSE ) {
				if ( compKey != 0 && compKey == reinterpret_cast<ULONG_PTR>( this ) ) {
					break;
				} else {
					Lock lock( mWatchesLock );
					WatchCallback( numOfBytes, ov );
				}
			}
```
if GetQueuedCompletionStatus is ok, and than will call `Lock lock( mWatchesLock );`.
but before call it, user call removeWatch, then WatchCallback will access null pointer.

**Comment by SpartanJ** [comment]
> this do not HeapFree pWatch.

I think you're right. Sorry, this is very old code, I should review it again.

> if GetQueuedCompletionStatus is ok, and than will call Lock lock( mWatchesLock );.
> but before call it, user call removeWatch, then WatchCallback will access null pointer.

You're correct, after the lock it should check that the overlapped object is still available.

I'll fix them next week since I don't have access to a Windows machine right now and I would like to test the fix.

Thanks for taking a look at the implementation!

**Comment by SpartanJ** [comment]
Memory lean fixed [here](https://github.com/SpartanJ/efsw/commit/43355523655e983ee3194325653c7dd9809bab14). And possible incorrect memory access fixed [here](https://github.com/SpartanJ/efsw/commit/621939d19c156e018ec311d742646fbe7dc432b1).
