### ISSUE TITLE
it works good on windows10 and11,but why does it not work on windowsserver2012R2?

### ISSUE THREAD

**Issue by Vdeilae** [SpartanJ/efsw#183]

**Comment by SpartanJ** [comment]
Ohhh I made a stupid mistake in one of the latest commits, I already pushed a fix [here](https://github.com/SpartanJ/efsw/commit/0079548dba2b5e153b8e259b7045eefb4daeaeac).

**Comment by Vdeilae** [comment]
thanks,bro,it works now,you really make a good job!
