### ISSUE TITLE
Failed to compile with LLVM 19.0.1

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/efsw#184]
See https://github.com/mstorsjo/llvm-mingw/issues/455.

**Comment by SpartanJ** [comment]
Damn, that's really problematic, affects also eepp. I guess I'll have to switch to char32_t, but i'll check later how it affects implementation.

**Comment by SpartanJ** [comment]
I forgot that I already migrated in eepp (they both implement a String class), so it's safe here to migrate. Fixed: [here](https://github.com/SpartanJ/efsw/commit/a064eb20e1312634813c724acc3c8229cc04e0a2).

**Comment by Curculigo** [comment]
Nope. It's not fixed. Please see the comment by @mstorsjo [here](https://github.com/mstorsjo/llvm-mingw/issues/455#issuecomment-2367881898).

**Comment by SpartanJ** [comment]
:shrug: 
I did exactly what it saids there: char32_t should be supported for char_traits which is [std::u32string](https://cplusplus.com/reference/string/u32string/), part of the standards. So no idea what's going on.

**Comment by Curculigo** [comment]
I switched to use w64devkit to have the environment like you. And you switched to MSYS2 to have the environment like me :joy:

**Comment by Curculigo** [comment]
I didn't notice that it's now no longer efsw's problem but eepp's. I will make a new issue for it on eepp's repo.
