### ISSUE TITLE
Modifying a file content led to notify twice for MacOS (FSEvent)

### ISSUE THREAD

**Issue by ritalin** [SpartanJ/efsw#186]
### What happens?

When I've modified a file content inside watching directory, a notification has occurred twice.

1st time: `kFSEventStreamEventFlagItemInodeMetaMod` was only on.
This will be notifying timestamp modification only.

2nd time: `kFSEventStreamEventFlagItemInodeMetaMod` and `kFSEventStreamEventFlagItemModified` was both on.

In current implementation, these are not distinguished.
So notification is twice.

### Solution proposal

It seems to add a changing file content or timestamp only option for `WatcherOption`.

### Environment

MacOS Ventura 13.6.9

**Comment by SpartanJ** [comment]
FSEvents is a little more fine grained than other OS watches, I consider the current behaviour correct (both events refer to a modification, if I remove any of those events we will omitting relevant information) but I guess this could be configured with a watcher option by exposing the bit-flags used to identify a modification event. I'll add it when I have some time.

**Comment by SpartanJ** [comment]
Added [Option::MacModifiedFilter](https://github.com/SpartanJ/efsw/commit/12d284322aef955d14081c1f1ee41ec38e7c47a0#diff-458521ab2965096b46f46c49469b8feb238d031710fc14a1556b942676d07dd4R146).
