### ISSUE TITLE
Doxygen support

### ISSUE THREAD

**Issue by CojocaruLiviuGabriel** [SpartanJ/efsw#188]
# Idea

Is support for an official documentation a desire for more people or is it only me? If yes, maybe doxygen is a good idea.

**Comment by SpartanJ** [comment]
Hi!
I'm not sure if it makes much sense for such a small library. Everything is already documented in the [efsw.hpp](https://github.com/SpartanJ/efsw/blob/master/include/efsw/efsw.hpp) header. 

Just curious: why do you think it could be useful? This is the first time someone ask for documentation (this library is more than 10 years old). Do you need help using it?

**Comment by CojocaruLiviuGabriel** [comment]
Had some problems regarding the Action::Modified, when I use C++ Filesystem to duplicate/copy/move files it is triggered everytime, resulting in multiple executions of the event.

**Comment by SpartanJ** [comment]
Added a clarification about modified files in the README file. I think that Doxygen is overkill for this small library.
