### ISSUE TITLE
FSEvents backend does not handle non-canonized paths.

### ISSUE THREAD

**Issue by vicproon** [SpartanJ/efsw#189]
# Issue Description
I am developing a folder monitor app on macOS.
I tried to monitor the `"."` folder but got no events in Listener callback.
After switching to generic watcher the events appeared.

# Investigation
I debugged the issue and it seems to be [this check](https://github.com/SpartanJ/efsw/blob/master/src/efsw/WatcherFSEvents.cpp#L111) that is causing the issue. 
Looks like the FSEvents API provides canonical paths for watched files, so it won't also work for paths like `"../"`, `"/absolute/path/to/dir/with/extra/slash/at/the/end//"`.
It also clear that the error appears only for non-recursice directory watch.

Brief view through the [FSEvents docs](https://developer.apple.com/documentation/coreservices/fseventstreamcallback) didn't give any insights if this behavior can be configured.

Also I found that the `FileWatcherFSEvents::pathInWatches` check would fail for equivalent paths since it literally compares strings: `"/path/to/dir"` and `"path/to/other/../dir"` would not be recognized as equivalent.

# Minimal code 

```main.cpp

#include <efsw/efsw.hpp>
#include <iostream>
#include <fstream>
#include <thread>

// #include <filesystem>

class UpdateListener : public efsw::FileWatchListener {
  public:
    void handleFileAction( efsw::WatchID watchid, const std::string& dir,
                           const std::string& filename, efsw::Action action,
                           std::string oldFilename ) override {
        switch ( action ) {
            case efsw::Actions::Add:
                std::cout << "DIR (" << dir << ") FILE (" << filename << ") has event Added"
                          << std::endl;
                break;
            case efsw::Actions::Delete:
                std::cout << "DIR (" << dir << ") FILE (" << filename << ") has event Delete"
                          << std::endl;
                break;
            case efsw::Actions::Modified:
                std::cout << "DIR (" << dir << ") FILE (" << filename << ") has event Modified"
                          << std::endl;
                break;
            case efsw::Actions::Moved:
                std::cout << "DIR (" << dir << ") FILE (" << filename << ") has event Moved from ("
                          << oldFilename << ")" << std::endl;
                break;
            default:
                std::cout << "Should never happen!" << std::endl;
        }
    }
};

int main() {
  efsw::FileWatcher* fileWatcher = new efsw::FileWatcher();
  UpdateListener* listener = new UpdateListener();

  // only happens in non-recursive watch
  efsw::WatchID watchID = fileWatcher->addWatch( ".", listener, false );
  // this one works. don't forget to #incldue <filesystem>, turn on c++17 and possibly link to std.
  // efsw::WatchID watchID = fileWatcher->addWatch( std::filesystem::canonical("."), listener, false );

  fileWatcher->watch();
  std::this_thread::sleep_for(std::chrono::milliseconds(100)); // had to add sleep for minimal example to work
  std::ofstream("tmp.txt") << "hello!" << std::endl;

  std::this_thread::sleep_for(std::chrono::milliseconds(100)); //  // had to add sleep for minimal example to work
  return 0;
}
```

This example based on the one from README.md fails to catch the tmp.txt modification event. 
However when the path is canonized, it outputs smth like this: 
`DIR (/path/to/working/directory) FILE (tmp.txt) has event Modified`

# Suggested fix
I think the possible way of fixing this is to canonize the `Directory` variable when the `addWatch` is called.
Also a check for canonical path `addWatch` with the return of error code is possible, provided that it is documented.

I fixed the issue on my side by using the c++17 `std::filesystem::canonical` before passing path to `addWatch`.
However since the efsw project uses only c++11 a correct library fix would require implementing the canonize method (possibly expanding the `efsw::FileSystem` API) which requires too much work.
Upgrading to c++17/20 for this fix seems like an overkill.
Maybe there is a macOS API to get canonical paths, that would be a nice fix.

# Version info
I used `efsw/1.4.0` conan package with `apple-clang 16` on `macOS Sequia 15.1`, but i don't really think it matters much for this particular issue.

**Comment by SpartanJ** [comment]
Hi! Thanks for reporting it, it should be fixed since [this commit](https://github.com/SpartanJ/efsw/commit/a3ca44b619f18e1436eae0c0b496fdf03bda2d72). If you're using conan you'll have to wait for an update on the package there, I'm not the maintainer, but I just added a new tag [1.4.1](https://github.com/SpartanJ/efsw/releases/tag/1.4.1) so people can start updating since there are several new fixes.
